version: '3.7'

services:

  db-mariadb:
    image: mariadb
    hostname: db-mariadb
    container_name: db-mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: application_data
    volumes:
      - ./.db:/var/lib/mysql

  db-adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db-mariadb
    ports:
      - 9000:8080
    depends_on:
      - db-mariadb