#Application Configuration
server:
  port: 8080

authentication:
  secret-key: "tA9xvUE5XLbktk6wbXRSF5ZLDUoiCdnfacYj96BFkYwG1Ufpp7LJ+bfl2d7jZEssYAm5Hq3tiF2cw3ctU5Nzwg=="

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:mariadb://localhost:3306/application_data
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN


logging:
  level:
    '[com.abb.pfg]': info
    '[org.hibernate]' : info
    '[org.springframework.security]': debug
    '[org.springframework.web]' : debug
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
